#!/bin/sh
set -e

ROOT="$(cd "$(dirname "$0")" && pwd)"

# Root
make -C "$ROOT"

# Sub-projects
make -C "$ROOT/1. daemon-socket"
make -C "$ROOT/2. launcher-standalone"
make -C "$ROOT/3. qua-convert"
make -C "$ROOT/4. x11-hotkeys-daemon"
