#!/bin/sh

exec qua-setup "$1" 0</dev/null 1>/dev/null 2>&1 

#exec setsid qua-setup "$1" 0</dev/null 1>/dev/null 2>&1 3>&- 4>&- 5>&- 6>&- #&
#(setsid sh -c "exec qua-setup \"$1\" 0</dev/null 1>/dev/null 2>&1 3>&- 4>&- 5>&- 6>&- &" &)
exit 0


